// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Packet.proto

package me.linx.vchat.core.packet;

public final class Packet {
  private Packet() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code PacketType}
   */
  public enum PacketType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>AUTH = 0;</code>
     */
    AUTH(0),
    /**
     * <code>TEXT = 1;</code>
     */
    TEXT(1),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>AUTH = 0;</code>
     */
    public static final int AUTH_VALUE = 0;
    /**
     * <code>TEXT = 1;</code>
     */
    public static final int TEXT_VALUE = 1;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static PacketType valueOf(int value) {
      return forNumber(value);
    }

    public static PacketType forNumber(int value) {
      switch (value) {
        case 0: return AUTH;
        case 1: return TEXT;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<PacketType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        PacketType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<PacketType>() {
            public PacketType findValueByNumber(int number) {
              return PacketType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return me.linx.vchat.core.packet.Packet.getDescriptor().getEnumTypes().get(0);
    }

    private static final PacketType[] VALUES = values();

    public static PacketType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private PacketType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:PacketType)
  }

  public interface PacketBoxOrBuilder extends
      // @@protoc_insertion_point(interface_extends:PacketBox)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.PacketType type = 1;</code>
     */
    int getTypeValue();
    /**
     * <code>.PacketType type = 1;</code>
     */
    me.linx.vchat.core.packet.Packet.PacketType getType();

    /**
     * <code>.AuthPacket authPacket = 2;</code>
     */
    boolean hasAuthPacket();
    /**
     * <code>.AuthPacket authPacket = 2;</code>
     */
    me.linx.vchat.core.packet.Packet.AuthPacket getAuthPacket();
    /**
     * <code>.AuthPacket authPacket = 2;</code>
     */
    me.linx.vchat.core.packet.Packet.AuthPacketOrBuilder getAuthPacketOrBuilder();

    /**
     * <code>.TextPacket textPacket = 3;</code>
     */
    boolean hasTextPacket();
    /**
     * <code>.TextPacket textPacket = 3;</code>
     */
    me.linx.vchat.core.packet.Packet.TextPacket getTextPacket();
    /**
     * <code>.TextPacket textPacket = 3;</code>
     */
    me.linx.vchat.core.packet.Packet.TextPacketOrBuilder getTextPacketOrBuilder();

    public me.linx.vchat.core.packet.Packet.PacketBox.PacketCase getPacketCase();
  }
  /**
   * Protobuf type {@code PacketBox}
   */
  public  static final class PacketBox extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:PacketBox)
      PacketBoxOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use PacketBox.newBuilder() to construct.
    private PacketBox(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private PacketBox() {
      type_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private PacketBox(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              int rawValue = input.readEnum();

              type_ = rawValue;
              break;
            }
            case 18: {
              me.linx.vchat.core.packet.Packet.AuthPacket.Builder subBuilder = null;
              if (packetCase_ == 2) {
                subBuilder = ((me.linx.vchat.core.packet.Packet.AuthPacket) packet_).toBuilder();
              }
              packet_ =
                  input.readMessage(me.linx.vchat.core.packet.Packet.AuthPacket.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((me.linx.vchat.core.packet.Packet.AuthPacket) packet_);
                packet_ = subBuilder.buildPartial();
              }
              packetCase_ = 2;
              break;
            }
            case 26: {
              me.linx.vchat.core.packet.Packet.TextPacket.Builder subBuilder = null;
              if (packetCase_ == 3) {
                subBuilder = ((me.linx.vchat.core.packet.Packet.TextPacket) packet_).toBuilder();
              }
              packet_ =
                  input.readMessage(me.linx.vchat.core.packet.Packet.TextPacket.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((me.linx.vchat.core.packet.Packet.TextPacket) packet_);
                packet_ = subBuilder.buildPartial();
              }
              packetCase_ = 3;
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return me.linx.vchat.core.packet.Packet.internal_static_PacketBox_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return me.linx.vchat.core.packet.Packet.internal_static_PacketBox_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              me.linx.vchat.core.packet.Packet.PacketBox.class, me.linx.vchat.core.packet.Packet.PacketBox.Builder.class);
    }

    private int packetCase_ = 0;
    private java.lang.Object packet_;
    public enum PacketCase
        implements com.google.protobuf.Internal.EnumLite {
      AUTHPACKET(2),
      TEXTPACKET(3),
      PACKET_NOT_SET(0);
      private final int value;
      private PacketCase(int value) {
        this.value = value;
      }
      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static PacketCase valueOf(int value) {
        return forNumber(value);
      }

      public static PacketCase forNumber(int value) {
        switch (value) {
          case 2: return AUTHPACKET;
          case 3: return TEXTPACKET;
          case 0: return PACKET_NOT_SET;
          default: return null;
        }
      }
      public int getNumber() {
        return this.value;
      }
    };

    public PacketCase
    getPacketCase() {
      return PacketCase.forNumber(
          packetCase_);
    }

    public static final int TYPE_FIELD_NUMBER = 1;
    private int type_;
    /**
     * <code>.PacketType type = 1;</code>
     */
    public int getTypeValue() {
      return type_;
    }
    /**
     * <code>.PacketType type = 1;</code>
     */
    public me.linx.vchat.core.packet.Packet.PacketType getType() {
      @SuppressWarnings("deprecation")
      me.linx.vchat.core.packet.Packet.PacketType result = me.linx.vchat.core.packet.Packet.PacketType.valueOf(type_);
      return result == null ? me.linx.vchat.core.packet.Packet.PacketType.UNRECOGNIZED : result;
    }

    public static final int AUTHPACKET_FIELD_NUMBER = 2;
    /**
     * <code>.AuthPacket authPacket = 2;</code>
     */
    public boolean hasAuthPacket() {
      return packetCase_ == 2;
    }
    /**
     * <code>.AuthPacket authPacket = 2;</code>
     */
    public me.linx.vchat.core.packet.Packet.AuthPacket getAuthPacket() {
      if (packetCase_ == 2) {
         return (me.linx.vchat.core.packet.Packet.AuthPacket) packet_;
      }
      return me.linx.vchat.core.packet.Packet.AuthPacket.getDefaultInstance();
    }
    /**
     * <code>.AuthPacket authPacket = 2;</code>
     */
    public me.linx.vchat.core.packet.Packet.AuthPacketOrBuilder getAuthPacketOrBuilder() {
      if (packetCase_ == 2) {
         return (me.linx.vchat.core.packet.Packet.AuthPacket) packet_;
      }
      return me.linx.vchat.core.packet.Packet.AuthPacket.getDefaultInstance();
    }

    public static final int TEXTPACKET_FIELD_NUMBER = 3;
    /**
     * <code>.TextPacket textPacket = 3;</code>
     */
    public boolean hasTextPacket() {
      return packetCase_ == 3;
    }
    /**
     * <code>.TextPacket textPacket = 3;</code>
     */
    public me.linx.vchat.core.packet.Packet.TextPacket getTextPacket() {
      if (packetCase_ == 3) {
         return (me.linx.vchat.core.packet.Packet.TextPacket) packet_;
      }
      return me.linx.vchat.core.packet.Packet.TextPacket.getDefaultInstance();
    }
    /**
     * <code>.TextPacket textPacket = 3;</code>
     */
    public me.linx.vchat.core.packet.Packet.TextPacketOrBuilder getTextPacketOrBuilder() {
      if (packetCase_ == 3) {
         return (me.linx.vchat.core.packet.Packet.TextPacket) packet_;
      }
      return me.linx.vchat.core.packet.Packet.TextPacket.getDefaultInstance();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (type_ != me.linx.vchat.core.packet.Packet.PacketType.AUTH.getNumber()) {
        output.writeEnum(1, type_);
      }
      if (packetCase_ == 2) {
        output.writeMessage(2, (me.linx.vchat.core.packet.Packet.AuthPacket) packet_);
      }
      if (packetCase_ == 3) {
        output.writeMessage(3, (me.linx.vchat.core.packet.Packet.TextPacket) packet_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (type_ != me.linx.vchat.core.packet.Packet.PacketType.AUTH.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, type_);
      }
      if (packetCase_ == 2) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, (me.linx.vchat.core.packet.Packet.AuthPacket) packet_);
      }
      if (packetCase_ == 3) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, (me.linx.vchat.core.packet.Packet.TextPacket) packet_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof me.linx.vchat.core.packet.Packet.PacketBox)) {
        return super.equals(obj);
      }
      me.linx.vchat.core.packet.Packet.PacketBox other = (me.linx.vchat.core.packet.Packet.PacketBox) obj;

      boolean result = true;
      result = result && type_ == other.type_;
      result = result && getPacketCase().equals(
          other.getPacketCase());
      if (!result) return false;
      switch (packetCase_) {
        case 2:
          result = result && getAuthPacket()
              .equals(other.getAuthPacket());
          break;
        case 3:
          result = result && getTextPacket()
              .equals(other.getTextPacket());
          break;
        case 0:
        default:
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + type_;
      switch (packetCase_) {
        case 2:
          hash = (37 * hash) + AUTHPACKET_FIELD_NUMBER;
          hash = (53 * hash) + getAuthPacket().hashCode();
          break;
        case 3:
          hash = (37 * hash) + TEXTPACKET_FIELD_NUMBER;
          hash = (53 * hash) + getTextPacket().hashCode();
          break;
        case 0:
        default:
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static me.linx.vchat.core.packet.Packet.PacketBox parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static me.linx.vchat.core.packet.Packet.PacketBox parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static me.linx.vchat.core.packet.Packet.PacketBox parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static me.linx.vchat.core.packet.Packet.PacketBox parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static me.linx.vchat.core.packet.Packet.PacketBox parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static me.linx.vchat.core.packet.Packet.PacketBox parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static me.linx.vchat.core.packet.Packet.PacketBox parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static me.linx.vchat.core.packet.Packet.PacketBox parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static me.linx.vchat.core.packet.Packet.PacketBox parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static me.linx.vchat.core.packet.Packet.PacketBox parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static me.linx.vchat.core.packet.Packet.PacketBox parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static me.linx.vchat.core.packet.Packet.PacketBox parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(me.linx.vchat.core.packet.Packet.PacketBox prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code PacketBox}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:PacketBox)
        me.linx.vchat.core.packet.Packet.PacketBoxOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return me.linx.vchat.core.packet.Packet.internal_static_PacketBox_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return me.linx.vchat.core.packet.Packet.internal_static_PacketBox_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                me.linx.vchat.core.packet.Packet.PacketBox.class, me.linx.vchat.core.packet.Packet.PacketBox.Builder.class);
      }

      // Construct using me.linx.vchat.core.packet.Packet.PacketBox.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        type_ = 0;

        packetCase_ = 0;
        packet_ = null;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return me.linx.vchat.core.packet.Packet.internal_static_PacketBox_descriptor;
      }

      @java.lang.Override
      public me.linx.vchat.core.packet.Packet.PacketBox getDefaultInstanceForType() {
        return me.linx.vchat.core.packet.Packet.PacketBox.getDefaultInstance();
      }

      @java.lang.Override
      public me.linx.vchat.core.packet.Packet.PacketBox build() {
        me.linx.vchat.core.packet.Packet.PacketBox result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public me.linx.vchat.core.packet.Packet.PacketBox buildPartial() {
        me.linx.vchat.core.packet.Packet.PacketBox result = new me.linx.vchat.core.packet.Packet.PacketBox(this);
        result.type_ = type_;
        if (packetCase_ == 2) {
          if (authPacketBuilder_ == null) {
            result.packet_ = packet_;
          } else {
            result.packet_ = authPacketBuilder_.build();
          }
        }
        if (packetCase_ == 3) {
          if (textPacketBuilder_ == null) {
            result.packet_ = packet_;
          } else {
            result.packet_ = textPacketBuilder_.build();
          }
        }
        result.packetCase_ = packetCase_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof me.linx.vchat.core.packet.Packet.PacketBox) {
          return mergeFrom((me.linx.vchat.core.packet.Packet.PacketBox)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(me.linx.vchat.core.packet.Packet.PacketBox other) {
        if (other == me.linx.vchat.core.packet.Packet.PacketBox.getDefaultInstance()) return this;
        if (other.type_ != 0) {
          setTypeValue(other.getTypeValue());
        }
        switch (other.getPacketCase()) {
          case AUTHPACKET: {
            mergeAuthPacket(other.getAuthPacket());
            break;
          }
          case TEXTPACKET: {
            mergeTextPacket(other.getTextPacket());
            break;
          }
          case PACKET_NOT_SET: {
            break;
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        me.linx.vchat.core.packet.Packet.PacketBox parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (me.linx.vchat.core.packet.Packet.PacketBox) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int packetCase_ = 0;
      private java.lang.Object packet_;
      public PacketCase
          getPacketCase() {
        return PacketCase.forNumber(
            packetCase_);
      }

      public Builder clearPacket() {
        packetCase_ = 0;
        packet_ = null;
        onChanged();
        return this;
      }


      private int type_ = 0;
      /**
       * <code>.PacketType type = 1;</code>
       */
      public int getTypeValue() {
        return type_;
      }
      /**
       * <code>.PacketType type = 1;</code>
       */
      public Builder setTypeValue(int value) {
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.PacketType type = 1;</code>
       */
      public me.linx.vchat.core.packet.Packet.PacketType getType() {
        @SuppressWarnings("deprecation")
        me.linx.vchat.core.packet.Packet.PacketType result = me.linx.vchat.core.packet.Packet.PacketType.valueOf(type_);
        return result == null ? me.linx.vchat.core.packet.Packet.PacketType.UNRECOGNIZED : result;
      }
      /**
       * <code>.PacketType type = 1;</code>
       */
      public Builder setType(me.linx.vchat.core.packet.Packet.PacketType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        type_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.PacketType type = 1;</code>
       */
      public Builder clearType() {
        
        type_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.SingleFieldBuilderV3<
          me.linx.vchat.core.packet.Packet.AuthPacket, me.linx.vchat.core.packet.Packet.AuthPacket.Builder, me.linx.vchat.core.packet.Packet.AuthPacketOrBuilder> authPacketBuilder_;
      /**
       * <code>.AuthPacket authPacket = 2;</code>
       */
      public boolean hasAuthPacket() {
        return packetCase_ == 2;
      }
      /**
       * <code>.AuthPacket authPacket = 2;</code>
       */
      public me.linx.vchat.core.packet.Packet.AuthPacket getAuthPacket() {
        if (authPacketBuilder_ == null) {
          if (packetCase_ == 2) {
            return (me.linx.vchat.core.packet.Packet.AuthPacket) packet_;
          }
          return me.linx.vchat.core.packet.Packet.AuthPacket.getDefaultInstance();
        } else {
          if (packetCase_ == 2) {
            return authPacketBuilder_.getMessage();
          }
          return me.linx.vchat.core.packet.Packet.AuthPacket.getDefaultInstance();
        }
      }
      /**
       * <code>.AuthPacket authPacket = 2;</code>
       */
      public Builder setAuthPacket(me.linx.vchat.core.packet.Packet.AuthPacket value) {
        if (authPacketBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          packet_ = value;
          onChanged();
        } else {
          authPacketBuilder_.setMessage(value);
        }
        packetCase_ = 2;
        return this;
      }
      /**
       * <code>.AuthPacket authPacket = 2;</code>
       */
      public Builder setAuthPacket(
          me.linx.vchat.core.packet.Packet.AuthPacket.Builder builderForValue) {
        if (authPacketBuilder_ == null) {
          packet_ = builderForValue.build();
          onChanged();
        } else {
          authPacketBuilder_.setMessage(builderForValue.build());
        }
        packetCase_ = 2;
        return this;
      }
      /**
       * <code>.AuthPacket authPacket = 2;</code>
       */
      public Builder mergeAuthPacket(me.linx.vchat.core.packet.Packet.AuthPacket value) {
        if (authPacketBuilder_ == null) {
          if (packetCase_ == 2 &&
              packet_ != me.linx.vchat.core.packet.Packet.AuthPacket.getDefaultInstance()) {
            packet_ = me.linx.vchat.core.packet.Packet.AuthPacket.newBuilder((me.linx.vchat.core.packet.Packet.AuthPacket) packet_)
                .mergeFrom(value).buildPartial();
          } else {
            packet_ = value;
          }
          onChanged();
        } else {
          if (packetCase_ == 2) {
            authPacketBuilder_.mergeFrom(value);
          }
          authPacketBuilder_.setMessage(value);
        }
        packetCase_ = 2;
        return this;
      }
      /**
       * <code>.AuthPacket authPacket = 2;</code>
       */
      public Builder clearAuthPacket() {
        if (authPacketBuilder_ == null) {
          if (packetCase_ == 2) {
            packetCase_ = 0;
            packet_ = null;
            onChanged();
          }
        } else {
          if (packetCase_ == 2) {
            packetCase_ = 0;
            packet_ = null;
          }
          authPacketBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>.AuthPacket authPacket = 2;</code>
       */
      public me.linx.vchat.core.packet.Packet.AuthPacket.Builder getAuthPacketBuilder() {
        return getAuthPacketFieldBuilder().getBuilder();
      }
      /**
       * <code>.AuthPacket authPacket = 2;</code>
       */
      public me.linx.vchat.core.packet.Packet.AuthPacketOrBuilder getAuthPacketOrBuilder() {
        if ((packetCase_ == 2) && (authPacketBuilder_ != null)) {
          return authPacketBuilder_.getMessageOrBuilder();
        } else {
          if (packetCase_ == 2) {
            return (me.linx.vchat.core.packet.Packet.AuthPacket) packet_;
          }
          return me.linx.vchat.core.packet.Packet.AuthPacket.getDefaultInstance();
        }
      }
      /**
       * <code>.AuthPacket authPacket = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          me.linx.vchat.core.packet.Packet.AuthPacket, me.linx.vchat.core.packet.Packet.AuthPacket.Builder, me.linx.vchat.core.packet.Packet.AuthPacketOrBuilder> 
          getAuthPacketFieldBuilder() {
        if (authPacketBuilder_ == null) {
          if (!(packetCase_ == 2)) {
            packet_ = me.linx.vchat.core.packet.Packet.AuthPacket.getDefaultInstance();
          }
          authPacketBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              me.linx.vchat.core.packet.Packet.AuthPacket, me.linx.vchat.core.packet.Packet.AuthPacket.Builder, me.linx.vchat.core.packet.Packet.AuthPacketOrBuilder>(
                  (me.linx.vchat.core.packet.Packet.AuthPacket) packet_,
                  getParentForChildren(),
                  isClean());
          packet_ = null;
        }
        packetCase_ = 2;
        onChanged();;
        return authPacketBuilder_;
      }

      private com.google.protobuf.SingleFieldBuilderV3<
          me.linx.vchat.core.packet.Packet.TextPacket, me.linx.vchat.core.packet.Packet.TextPacket.Builder, me.linx.vchat.core.packet.Packet.TextPacketOrBuilder> textPacketBuilder_;
      /**
       * <code>.TextPacket textPacket = 3;</code>
       */
      public boolean hasTextPacket() {
        return packetCase_ == 3;
      }
      /**
       * <code>.TextPacket textPacket = 3;</code>
       */
      public me.linx.vchat.core.packet.Packet.TextPacket getTextPacket() {
        if (textPacketBuilder_ == null) {
          if (packetCase_ == 3) {
            return (me.linx.vchat.core.packet.Packet.TextPacket) packet_;
          }
          return me.linx.vchat.core.packet.Packet.TextPacket.getDefaultInstance();
        } else {
          if (packetCase_ == 3) {
            return textPacketBuilder_.getMessage();
          }
          return me.linx.vchat.core.packet.Packet.TextPacket.getDefaultInstance();
        }
      }
      /**
       * <code>.TextPacket textPacket = 3;</code>
       */
      public Builder setTextPacket(me.linx.vchat.core.packet.Packet.TextPacket value) {
        if (textPacketBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          packet_ = value;
          onChanged();
        } else {
          textPacketBuilder_.setMessage(value);
        }
        packetCase_ = 3;
        return this;
      }
      /**
       * <code>.TextPacket textPacket = 3;</code>
       */
      public Builder setTextPacket(
          me.linx.vchat.core.packet.Packet.TextPacket.Builder builderForValue) {
        if (textPacketBuilder_ == null) {
          packet_ = builderForValue.build();
          onChanged();
        } else {
          textPacketBuilder_.setMessage(builderForValue.build());
        }
        packetCase_ = 3;
        return this;
      }
      /**
       * <code>.TextPacket textPacket = 3;</code>
       */
      public Builder mergeTextPacket(me.linx.vchat.core.packet.Packet.TextPacket value) {
        if (textPacketBuilder_ == null) {
          if (packetCase_ == 3 &&
              packet_ != me.linx.vchat.core.packet.Packet.TextPacket.getDefaultInstance()) {
            packet_ = me.linx.vchat.core.packet.Packet.TextPacket.newBuilder((me.linx.vchat.core.packet.Packet.TextPacket) packet_)
                .mergeFrom(value).buildPartial();
          } else {
            packet_ = value;
          }
          onChanged();
        } else {
          if (packetCase_ == 3) {
            textPacketBuilder_.mergeFrom(value);
          }
          textPacketBuilder_.setMessage(value);
        }
        packetCase_ = 3;
        return this;
      }
      /**
       * <code>.TextPacket textPacket = 3;</code>
       */
      public Builder clearTextPacket() {
        if (textPacketBuilder_ == null) {
          if (packetCase_ == 3) {
            packetCase_ = 0;
            packet_ = null;
            onChanged();
          }
        } else {
          if (packetCase_ == 3) {
            packetCase_ = 0;
            packet_ = null;
          }
          textPacketBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>.TextPacket textPacket = 3;</code>
       */
      public me.linx.vchat.core.packet.Packet.TextPacket.Builder getTextPacketBuilder() {
        return getTextPacketFieldBuilder().getBuilder();
      }
      /**
       * <code>.TextPacket textPacket = 3;</code>
       */
      public me.linx.vchat.core.packet.Packet.TextPacketOrBuilder getTextPacketOrBuilder() {
        if ((packetCase_ == 3) && (textPacketBuilder_ != null)) {
          return textPacketBuilder_.getMessageOrBuilder();
        } else {
          if (packetCase_ == 3) {
            return (me.linx.vchat.core.packet.Packet.TextPacket) packet_;
          }
          return me.linx.vchat.core.packet.Packet.TextPacket.getDefaultInstance();
        }
      }
      /**
       * <code>.TextPacket textPacket = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          me.linx.vchat.core.packet.Packet.TextPacket, me.linx.vchat.core.packet.Packet.TextPacket.Builder, me.linx.vchat.core.packet.Packet.TextPacketOrBuilder> 
          getTextPacketFieldBuilder() {
        if (textPacketBuilder_ == null) {
          if (!(packetCase_ == 3)) {
            packet_ = me.linx.vchat.core.packet.Packet.TextPacket.getDefaultInstance();
          }
          textPacketBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              me.linx.vchat.core.packet.Packet.TextPacket, me.linx.vchat.core.packet.Packet.TextPacket.Builder, me.linx.vchat.core.packet.Packet.TextPacketOrBuilder>(
                  (me.linx.vchat.core.packet.Packet.TextPacket) packet_,
                  getParentForChildren(),
                  isClean());
          packet_ = null;
        }
        packetCase_ = 3;
        onChanged();;
        return textPacketBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:PacketBox)
    }

    // @@protoc_insertion_point(class_scope:PacketBox)
    private static final me.linx.vchat.core.packet.Packet.PacketBox DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new me.linx.vchat.core.packet.Packet.PacketBox();
    }

    public static me.linx.vchat.core.packet.Packet.PacketBox getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<PacketBox>
        PARSER = new com.google.protobuf.AbstractParser<PacketBox>() {
      @java.lang.Override
      public PacketBox parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new PacketBox(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<PacketBox> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PacketBox> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public me.linx.vchat.core.packet.Packet.PacketBox getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface AuthPacketOrBuilder extends
      // @@protoc_insertion_point(interface_extends:AuthPacket)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int64 user_id = 1;</code>
     */
    long getUserId();

    /**
     * <code>string token = 2;</code>
     */
    java.lang.String getToken();
    /**
     * <code>string token = 2;</code>
     */
    com.google.protobuf.ByteString
        getTokenBytes();
  }
  /**
   * Protobuf type {@code AuthPacket}
   */
  public  static final class AuthPacket extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:AuthPacket)
      AuthPacketOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use AuthPacket.newBuilder() to construct.
    private AuthPacket(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private AuthPacket() {
      userId_ = 0L;
      token_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private AuthPacket(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              userId_ = input.readInt64();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              token_ = s;
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return me.linx.vchat.core.packet.Packet.internal_static_AuthPacket_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return me.linx.vchat.core.packet.Packet.internal_static_AuthPacket_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              me.linx.vchat.core.packet.Packet.AuthPacket.class, me.linx.vchat.core.packet.Packet.AuthPacket.Builder.class);
    }

    public static final int USER_ID_FIELD_NUMBER = 1;
    private long userId_;
    /**
     * <code>int64 user_id = 1;</code>
     */
    public long getUserId() {
      return userId_;
    }

    public static final int TOKEN_FIELD_NUMBER = 2;
    private volatile java.lang.Object token_;
    /**
     * <code>string token = 2;</code>
     */
    public java.lang.String getToken() {
      java.lang.Object ref = token_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        token_ = s;
        return s;
      }
    }
    /**
     * <code>string token = 2;</code>
     */
    public com.google.protobuf.ByteString
        getTokenBytes() {
      java.lang.Object ref = token_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        token_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (userId_ != 0L) {
        output.writeInt64(1, userId_);
      }
      if (!getTokenBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, token_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (userId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, userId_);
      }
      if (!getTokenBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, token_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof me.linx.vchat.core.packet.Packet.AuthPacket)) {
        return super.equals(obj);
      }
      me.linx.vchat.core.packet.Packet.AuthPacket other = (me.linx.vchat.core.packet.Packet.AuthPacket) obj;

      boolean result = true;
      result = result && (getUserId()
          == other.getUserId());
      result = result && getToken()
          .equals(other.getToken());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + USER_ID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getUserId());
      hash = (37 * hash) + TOKEN_FIELD_NUMBER;
      hash = (53 * hash) + getToken().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static me.linx.vchat.core.packet.Packet.AuthPacket parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static me.linx.vchat.core.packet.Packet.AuthPacket parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static me.linx.vchat.core.packet.Packet.AuthPacket parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static me.linx.vchat.core.packet.Packet.AuthPacket parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static me.linx.vchat.core.packet.Packet.AuthPacket parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static me.linx.vchat.core.packet.Packet.AuthPacket parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static me.linx.vchat.core.packet.Packet.AuthPacket parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static me.linx.vchat.core.packet.Packet.AuthPacket parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static me.linx.vchat.core.packet.Packet.AuthPacket parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static me.linx.vchat.core.packet.Packet.AuthPacket parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static me.linx.vchat.core.packet.Packet.AuthPacket parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static me.linx.vchat.core.packet.Packet.AuthPacket parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(me.linx.vchat.core.packet.Packet.AuthPacket prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code AuthPacket}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:AuthPacket)
        me.linx.vchat.core.packet.Packet.AuthPacketOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return me.linx.vchat.core.packet.Packet.internal_static_AuthPacket_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return me.linx.vchat.core.packet.Packet.internal_static_AuthPacket_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                me.linx.vchat.core.packet.Packet.AuthPacket.class, me.linx.vchat.core.packet.Packet.AuthPacket.Builder.class);
      }

      // Construct using me.linx.vchat.core.packet.Packet.AuthPacket.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        userId_ = 0L;

        token_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return me.linx.vchat.core.packet.Packet.internal_static_AuthPacket_descriptor;
      }

      @java.lang.Override
      public me.linx.vchat.core.packet.Packet.AuthPacket getDefaultInstanceForType() {
        return me.linx.vchat.core.packet.Packet.AuthPacket.getDefaultInstance();
      }

      @java.lang.Override
      public me.linx.vchat.core.packet.Packet.AuthPacket build() {
        me.linx.vchat.core.packet.Packet.AuthPacket result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public me.linx.vchat.core.packet.Packet.AuthPacket buildPartial() {
        me.linx.vchat.core.packet.Packet.AuthPacket result = new me.linx.vchat.core.packet.Packet.AuthPacket(this);
        result.userId_ = userId_;
        result.token_ = token_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof me.linx.vchat.core.packet.Packet.AuthPacket) {
          return mergeFrom((me.linx.vchat.core.packet.Packet.AuthPacket)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(me.linx.vchat.core.packet.Packet.AuthPacket other) {
        if (other == me.linx.vchat.core.packet.Packet.AuthPacket.getDefaultInstance()) return this;
        if (other.getUserId() != 0L) {
          setUserId(other.getUserId());
        }
        if (!other.getToken().isEmpty()) {
          token_ = other.token_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        me.linx.vchat.core.packet.Packet.AuthPacket parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (me.linx.vchat.core.packet.Packet.AuthPacket) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long userId_ ;
      /**
       * <code>int64 user_id = 1;</code>
       */
      public long getUserId() {
        return userId_;
      }
      /**
       * <code>int64 user_id = 1;</code>
       */
      public Builder setUserId(long value) {
        
        userId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 user_id = 1;</code>
       */
      public Builder clearUserId() {
        
        userId_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object token_ = "";
      /**
       * <code>string token = 2;</code>
       */
      public java.lang.String getToken() {
        java.lang.Object ref = token_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          token_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string token = 2;</code>
       */
      public com.google.protobuf.ByteString
          getTokenBytes() {
        java.lang.Object ref = token_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          token_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string token = 2;</code>
       */
      public Builder setToken(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        token_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string token = 2;</code>
       */
      public Builder clearToken() {
        
        token_ = getDefaultInstance().getToken();
        onChanged();
        return this;
      }
      /**
       * <code>string token = 2;</code>
       */
      public Builder setTokenBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        token_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:AuthPacket)
    }

    // @@protoc_insertion_point(class_scope:AuthPacket)
    private static final me.linx.vchat.core.packet.Packet.AuthPacket DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new me.linx.vchat.core.packet.Packet.AuthPacket();
    }

    public static me.linx.vchat.core.packet.Packet.AuthPacket getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<AuthPacket>
        PARSER = new com.google.protobuf.AbstractParser<AuthPacket>() {
      @java.lang.Override
      public AuthPacket parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new AuthPacket(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<AuthPacket> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<AuthPacket> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public me.linx.vchat.core.packet.Packet.AuthPacket getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface TextPacketOrBuilder extends
      // @@protoc_insertion_point(interface_extends:TextPacket)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *发送者ID
     * </pre>
     *
     * <code>int64 from_id = 1;</code>
     */
    long getFromId();

    /**
     * <pre>
     *接收者ID
     * </pre>
     *
     * <code>int64 to_id = 2;</code>
     */
    long getToId();

    /**
     * <code>string msg = 3;</code>
     */
    java.lang.String getMsg();
    /**
     * <code>string msg = 3;</code>
     */
    com.google.protobuf.ByteString
        getMsgBytes();

    /**
     * <code>.google.protobuf.Timestamp create_time = 4;</code>
     */
    boolean hasCreateTime();
    /**
     * <code>.google.protobuf.Timestamp create_time = 4;</code>
     */
    com.google.protobuf.Timestamp getCreateTime();
    /**
     * <code>.google.protobuf.Timestamp create_time = 4;</code>
     */
    com.google.protobuf.TimestampOrBuilder getCreateTimeOrBuilder();
  }
  /**
   * Protobuf type {@code TextPacket}
   */
  public  static final class TextPacket extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:TextPacket)
      TextPacketOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use TextPacket.newBuilder() to construct.
    private TextPacket(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private TextPacket() {
      fromId_ = 0L;
      toId_ = 0L;
      msg_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private TextPacket(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              fromId_ = input.readInt64();
              break;
            }
            case 16: {

              toId_ = input.readInt64();
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              msg_ = s;
              break;
            }
            case 34: {
              com.google.protobuf.Timestamp.Builder subBuilder = null;
              if (createTime_ != null) {
                subBuilder = createTime_.toBuilder();
              }
              createTime_ = input.readMessage(com.google.protobuf.Timestamp.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(createTime_);
                createTime_ = subBuilder.buildPartial();
              }

              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return me.linx.vchat.core.packet.Packet.internal_static_TextPacket_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return me.linx.vchat.core.packet.Packet.internal_static_TextPacket_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              me.linx.vchat.core.packet.Packet.TextPacket.class, me.linx.vchat.core.packet.Packet.TextPacket.Builder.class);
    }

    public static final int FROM_ID_FIELD_NUMBER = 1;
    private long fromId_;
    /**
     * <pre>
     *发送者ID
     * </pre>
     *
     * <code>int64 from_id = 1;</code>
     */
    public long getFromId() {
      return fromId_;
    }

    public static final int TO_ID_FIELD_NUMBER = 2;
    private long toId_;
    /**
     * <pre>
     *接收者ID
     * </pre>
     *
     * <code>int64 to_id = 2;</code>
     */
    public long getToId() {
      return toId_;
    }

    public static final int MSG_FIELD_NUMBER = 3;
    private volatile java.lang.Object msg_;
    /**
     * <code>string msg = 3;</code>
     */
    public java.lang.String getMsg() {
      java.lang.Object ref = msg_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        msg_ = s;
        return s;
      }
    }
    /**
     * <code>string msg = 3;</code>
     */
    public com.google.protobuf.ByteString
        getMsgBytes() {
      java.lang.Object ref = msg_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        msg_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CREATE_TIME_FIELD_NUMBER = 4;
    private com.google.protobuf.Timestamp createTime_;
    /**
     * <code>.google.protobuf.Timestamp create_time = 4;</code>
     */
    public boolean hasCreateTime() {
      return createTime_ != null;
    }
    /**
     * <code>.google.protobuf.Timestamp create_time = 4;</code>
     */
    public com.google.protobuf.Timestamp getCreateTime() {
      return createTime_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : createTime_;
    }
    /**
     * <code>.google.protobuf.Timestamp create_time = 4;</code>
     */
    public com.google.protobuf.TimestampOrBuilder getCreateTimeOrBuilder() {
      return getCreateTime();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (fromId_ != 0L) {
        output.writeInt64(1, fromId_);
      }
      if (toId_ != 0L) {
        output.writeInt64(2, toId_);
      }
      if (!getMsgBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, msg_);
      }
      if (createTime_ != null) {
        output.writeMessage(4, getCreateTime());
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (fromId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, fromId_);
      }
      if (toId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, toId_);
      }
      if (!getMsgBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, msg_);
      }
      if (createTime_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, getCreateTime());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof me.linx.vchat.core.packet.Packet.TextPacket)) {
        return super.equals(obj);
      }
      me.linx.vchat.core.packet.Packet.TextPacket other = (me.linx.vchat.core.packet.Packet.TextPacket) obj;

      boolean result = true;
      result = result && (getFromId()
          == other.getFromId());
      result = result && (getToId()
          == other.getToId());
      result = result && getMsg()
          .equals(other.getMsg());
      result = result && (hasCreateTime() == other.hasCreateTime());
      if (hasCreateTime()) {
        result = result && getCreateTime()
            .equals(other.getCreateTime());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + FROM_ID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getFromId());
      hash = (37 * hash) + TO_ID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getToId());
      hash = (37 * hash) + MSG_FIELD_NUMBER;
      hash = (53 * hash) + getMsg().hashCode();
      if (hasCreateTime()) {
        hash = (37 * hash) + CREATE_TIME_FIELD_NUMBER;
        hash = (53 * hash) + getCreateTime().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static me.linx.vchat.core.packet.Packet.TextPacket parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static me.linx.vchat.core.packet.Packet.TextPacket parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static me.linx.vchat.core.packet.Packet.TextPacket parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static me.linx.vchat.core.packet.Packet.TextPacket parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static me.linx.vchat.core.packet.Packet.TextPacket parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static me.linx.vchat.core.packet.Packet.TextPacket parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static me.linx.vchat.core.packet.Packet.TextPacket parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static me.linx.vchat.core.packet.Packet.TextPacket parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static me.linx.vchat.core.packet.Packet.TextPacket parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static me.linx.vchat.core.packet.Packet.TextPacket parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static me.linx.vchat.core.packet.Packet.TextPacket parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static me.linx.vchat.core.packet.Packet.TextPacket parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(me.linx.vchat.core.packet.Packet.TextPacket prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code TextPacket}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:TextPacket)
        me.linx.vchat.core.packet.Packet.TextPacketOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return me.linx.vchat.core.packet.Packet.internal_static_TextPacket_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return me.linx.vchat.core.packet.Packet.internal_static_TextPacket_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                me.linx.vchat.core.packet.Packet.TextPacket.class, me.linx.vchat.core.packet.Packet.TextPacket.Builder.class);
      }

      // Construct using me.linx.vchat.core.packet.Packet.TextPacket.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        fromId_ = 0L;

        toId_ = 0L;

        msg_ = "";

        if (createTimeBuilder_ == null) {
          createTime_ = null;
        } else {
          createTime_ = null;
          createTimeBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return me.linx.vchat.core.packet.Packet.internal_static_TextPacket_descriptor;
      }

      @java.lang.Override
      public me.linx.vchat.core.packet.Packet.TextPacket getDefaultInstanceForType() {
        return me.linx.vchat.core.packet.Packet.TextPacket.getDefaultInstance();
      }

      @java.lang.Override
      public me.linx.vchat.core.packet.Packet.TextPacket build() {
        me.linx.vchat.core.packet.Packet.TextPacket result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public me.linx.vchat.core.packet.Packet.TextPacket buildPartial() {
        me.linx.vchat.core.packet.Packet.TextPacket result = new me.linx.vchat.core.packet.Packet.TextPacket(this);
        result.fromId_ = fromId_;
        result.toId_ = toId_;
        result.msg_ = msg_;
        if (createTimeBuilder_ == null) {
          result.createTime_ = createTime_;
        } else {
          result.createTime_ = createTimeBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof me.linx.vchat.core.packet.Packet.TextPacket) {
          return mergeFrom((me.linx.vchat.core.packet.Packet.TextPacket)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(me.linx.vchat.core.packet.Packet.TextPacket other) {
        if (other == me.linx.vchat.core.packet.Packet.TextPacket.getDefaultInstance()) return this;
        if (other.getFromId() != 0L) {
          setFromId(other.getFromId());
        }
        if (other.getToId() != 0L) {
          setToId(other.getToId());
        }
        if (!other.getMsg().isEmpty()) {
          msg_ = other.msg_;
          onChanged();
        }
        if (other.hasCreateTime()) {
          mergeCreateTime(other.getCreateTime());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        me.linx.vchat.core.packet.Packet.TextPacket parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (me.linx.vchat.core.packet.Packet.TextPacket) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long fromId_ ;
      /**
       * <pre>
       *发送者ID
       * </pre>
       *
       * <code>int64 from_id = 1;</code>
       */
      public long getFromId() {
        return fromId_;
      }
      /**
       * <pre>
       *发送者ID
       * </pre>
       *
       * <code>int64 from_id = 1;</code>
       */
      public Builder setFromId(long value) {
        
        fromId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *发送者ID
       * </pre>
       *
       * <code>int64 from_id = 1;</code>
       */
      public Builder clearFromId() {
        
        fromId_ = 0L;
        onChanged();
        return this;
      }

      private long toId_ ;
      /**
       * <pre>
       *接收者ID
       * </pre>
       *
       * <code>int64 to_id = 2;</code>
       */
      public long getToId() {
        return toId_;
      }
      /**
       * <pre>
       *接收者ID
       * </pre>
       *
       * <code>int64 to_id = 2;</code>
       */
      public Builder setToId(long value) {
        
        toId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *接收者ID
       * </pre>
       *
       * <code>int64 to_id = 2;</code>
       */
      public Builder clearToId() {
        
        toId_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object msg_ = "";
      /**
       * <code>string msg = 3;</code>
       */
      public java.lang.String getMsg() {
        java.lang.Object ref = msg_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          msg_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string msg = 3;</code>
       */
      public com.google.protobuf.ByteString
          getMsgBytes() {
        java.lang.Object ref = msg_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          msg_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string msg = 3;</code>
       */
      public Builder setMsg(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        msg_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string msg = 3;</code>
       */
      public Builder clearMsg() {
        
        msg_ = getDefaultInstance().getMsg();
        onChanged();
        return this;
      }
      /**
       * <code>string msg = 3;</code>
       */
      public Builder setMsgBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        msg_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.Timestamp createTime_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> createTimeBuilder_;
      /**
       * <code>.google.protobuf.Timestamp create_time = 4;</code>
       */
      public boolean hasCreateTime() {
        return createTimeBuilder_ != null || createTime_ != null;
      }
      /**
       * <code>.google.protobuf.Timestamp create_time = 4;</code>
       */
      public com.google.protobuf.Timestamp getCreateTime() {
        if (createTimeBuilder_ == null) {
          return createTime_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : createTime_;
        } else {
          return createTimeBuilder_.getMessage();
        }
      }
      /**
       * <code>.google.protobuf.Timestamp create_time = 4;</code>
       */
      public Builder setCreateTime(com.google.protobuf.Timestamp value) {
        if (createTimeBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          createTime_ = value;
          onChanged();
        } else {
          createTimeBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp create_time = 4;</code>
       */
      public Builder setCreateTime(
          com.google.protobuf.Timestamp.Builder builderForValue) {
        if (createTimeBuilder_ == null) {
          createTime_ = builderForValue.build();
          onChanged();
        } else {
          createTimeBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp create_time = 4;</code>
       */
      public Builder mergeCreateTime(com.google.protobuf.Timestamp value) {
        if (createTimeBuilder_ == null) {
          if (createTime_ != null) {
            createTime_ =
              com.google.protobuf.Timestamp.newBuilder(createTime_).mergeFrom(value).buildPartial();
          } else {
            createTime_ = value;
          }
          onChanged();
        } else {
          createTimeBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp create_time = 4;</code>
       */
      public Builder clearCreateTime() {
        if (createTimeBuilder_ == null) {
          createTime_ = null;
          onChanged();
        } else {
          createTime_ = null;
          createTimeBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp create_time = 4;</code>
       */
      public com.google.protobuf.Timestamp.Builder getCreateTimeBuilder() {
        
        onChanged();
        return getCreateTimeFieldBuilder().getBuilder();
      }
      /**
       * <code>.google.protobuf.Timestamp create_time = 4;</code>
       */
      public com.google.protobuf.TimestampOrBuilder getCreateTimeOrBuilder() {
        if (createTimeBuilder_ != null) {
          return createTimeBuilder_.getMessageOrBuilder();
        } else {
          return createTime_ == null ?
              com.google.protobuf.Timestamp.getDefaultInstance() : createTime_;
        }
      }
      /**
       * <code>.google.protobuf.Timestamp create_time = 4;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
          getCreateTimeFieldBuilder() {
        if (createTimeBuilder_ == null) {
          createTimeBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                  getCreateTime(),
                  getParentForChildren(),
                  isClean());
          createTime_ = null;
        }
        return createTimeBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:TextPacket)
    }

    // @@protoc_insertion_point(class_scope:TextPacket)
    private static final me.linx.vchat.core.packet.Packet.TextPacket DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new me.linx.vchat.core.packet.Packet.TextPacket();
    }

    public static me.linx.vchat.core.packet.Packet.TextPacket getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<TextPacket>
        PARSER = new com.google.protobuf.AbstractParser<TextPacket>() {
      @java.lang.Override
      public TextPacket parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new TextPacket(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<TextPacket> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<TextPacket> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public me.linx.vchat.core.packet.Packet.TextPacket getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PacketBox_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PacketBox_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_AuthPacket_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_AuthPacket_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_TextPacket_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_TextPacket_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014Packet.proto\032\037google/protobuf/timestam" +
      "p.proto\"v\n\tPacketBox\022\031\n\004type\030\001 \001(\0162\013.Pac" +
      "ketType\022!\n\nauthPacket\030\002 \001(\0132\013.AuthPacket" +
      "H\000\022!\n\ntextPacket\030\003 \001(\0132\013.TextPacketH\000B\010\n" +
      "\006packet\",\n\nAuthPacket\022\017\n\007user_id\030\001 \001(\003\022\r" +
      "\n\005token\030\002 \001(\t\"j\n\nTextPacket\022\017\n\007from_id\030\001" +
      " \001(\003\022\r\n\005to_id\030\002 \001(\003\022\013\n\003msg\030\003 \001(\t\022/\n\013crea" +
      "te_time\030\004 \001(\0132\032.google.protobuf.Timestam" +
      "p* \n\nPacketType\022\010\n\004AUTH\020\000\022\010\n\004TEXT\020\001B%\n\031m" +
      "e.linx.vchat.core.packetB\006PacketH\001b\006prot" +
      "o3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.TimestampProto.getDescriptor(),
        }, assigner);
    internal_static_PacketBox_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_PacketBox_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PacketBox_descriptor,
        new java.lang.String[] { "Type", "AuthPacket", "TextPacket", "Packet", });
    internal_static_AuthPacket_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_AuthPacket_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_AuthPacket_descriptor,
        new java.lang.String[] { "UserId", "Token", });
    internal_static_TextPacket_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_TextPacket_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_TextPacket_descriptor,
        new java.lang.String[] { "FromId", "ToId", "Msg", "CreateTime", });
    com.google.protobuf.TimestampProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
